/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.proyecto.vistasClientes;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import mx.itson.proyectodb.entidades.Cliente;
import mx.itson.proyectodb.model.ClienteModel;

/**
 *
 * @author Admin
 */
public class ClienteJf extends javax.swing.JFrame {

  // Se crea una instancia de la clase ClienteModel.
// ClienteModel probablemente maneja la lógica relacionada con los clientes en la base de datos.
ClienteModel ClienteModel = new ClienteModel();

/**
 * Constructor que inicializa la interfaz gráfica y actualiza la tabla de clientes.
 */
public ClienteJf() {
    initComponents();
    // Llama al método actualizarTabla para cargar los datos de los clientes en la tabla.
    actualizarTabla();
}

/**
 * Método privado para actualizar la tabla de clientes en la interfaz gráfica.
 */
private void actualizarTabla() {
    // Se crea un modelo de tabla por defecto para manejar los datos de la tabla.
    DefaultTableModel datosTabla = new DefaultTableModel();

    // Se añaden las columnas a la tabla.
    datosTabla.addColumn("ID");
    datosTabla.addColumn("Nombre");
    datosTabla.addColumn("Apellido");
    datosTabla.addColumn("Email");

    // Se obtienen los clientes desde la base de datos a través del objeto ClienteModel.
    for (Cliente c : ClienteModel.select()) {
        // Se añaden las filas con la información de cada cliente a la tabla.
        datosTabla.addRow(
                new Object[]{
                    c.getId_cliente(),
                    c.getNombre(),
                    c.getApellido(),
                    // c.getEmail()
                });
    }

    // Se establece el modelo de la tabla en la interfaz gráfica.
    tbcliente.setModel(datosTabla);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txfbuscar = new javax.swing.JTextField();
        btBuscador = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbcliente);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de clientes");

        txfbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfbuscarActionPerformed(evt);
            }
        });

        btBuscador.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btBuscador.setText("Buscar");
        btBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(txfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("Agegar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Se crea una instancia de la clase ClienteAdd.
// ClienteAdd es probablemente una clase que extiende JFrame o JDialog y representa una ventana o diálogo para agregar clientes.
ClienteAdd cA = new ClienteAdd(null, true);

// Hace visible la instancia de ClienteAdd recién creada.
// Esto permite que la ventana o diálogo sea mostrado al usuario.
cA.setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txfbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfbuscarActionPerformed

    private void btBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscadorActionPerformed
// Obtener el texto ingresado en el campo de búsqueda
String buscar = txfbuscar.getText();

// Verificar si el campo de búsqueda está vacío
if (buscar.isEmpty()) {
    // Si está vacío, actualizar la tabla con la lista completa de Clientes
    this.actualizarTabla();
} else {
    // Si hay texto en el campo de búsqueda, realizar la búsqueda
    List<Cliente> busqueda = new ArrayList<>();

    // Iterar sobre la lista completa de Clientes y agregar aquellos que coincidan con el criterio de búsqueda
    for (Cliente cliente : Cliente.getAll(buscar)) {
        // Verificar si el nombre del Cliente contiene el texto de búsqueda (ignorar mayúsculas y minúsculas)
        if (cliente.getNombre().toLowerCase().contains(buscar.toLowerCase())) {
            busqueda.add(cliente);
        } else if (cliente.getNombre().toLowerCase().contains(buscar.toLowerCase())) {
            // Esta condición parece ser redundante, ya que es idéntica a la anterior
            // Puede ser un error y debería revisarse
            busqueda.add(cliente);
        }
    }

    // TODO: Hace falta lógica para mostrar el resultado de la búsqueda en la tabla
    // Actualizar la tabla con el resultado de la búsqueda (falta implementar esta parte)
    // this.actualizarTabla();
}

    }//GEN-LAST:event_btBuscadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteJf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteJf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteJf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteJf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteJf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbcliente;
    private javax.swing.JTextField txfbuscar;
    // End of variables declaration//GEN-END:variables
}
